// Graphic-design Galleries Data
// This file is auto-generated by update-galleries.js
// To update: add/remove images from gallery folders, then run: node update-galleries.js

const graphicDesignGalleries = [
  {
    id: "covers",
    title: "Music Artworks",
    description: "Covers of various tracks",
    images: [
      "covers/Visyura - Desolate (cover).png",
      "covers/Visyura - Anima Sola (cover).png",
      "covers/Visyura - EXPIATE (cover).png",
      "covers/Popbot, Juha, Visyura, jhl, Fehu., glyphli, Exorbiter, (un)familiar, lukasipo) - Rope (cover).png",
      "covers/Visyura - INNER FIELDS(cover).png",
      "covers/Visyura - AIMLESS (cover).png",
      "covers/Visyura - DISSOLVE (cover).png",
      "covers/Visyura - FRAGMENTS (cover).png",
      "covers/Visyura - ALLUVIUM (cover).png",
      "covers/Visyura - A Spurious Porspering (Concept).png",
    ],
    notes: [
      "Album cover for Desolate",
      "Album cover for Anima Sola",
      "Album cover for EXPIATE",
      "Compilation album cover featuring multiple artists",
      "Album cover for INNER FIELDS",
      "Album cover for AIMLESS",
      "Album cover for DISSOLVE",
      "Album cover for FRAGMENTS",
      "Album cover for ALLUVIUM",
      "Concept art for A Spurious Porspering",
    ]
  },
  {
    id: "svp-urgent",
    title: "SVP URGENT",
    description: "A weekly series with friends where each created visual art based on the same word",
    images: [
      "svp-urgent/vsy_svp6_bang.png",
      "svp-urgent/vsy_svp4_contain.png",
      "svp-urgent/vsy_svp3_bow.png",
      "svp-urgent/vsy_svp1_absorb.png",
    ],
    notes: [
      "SVP #6 - Bang",
      "SVP #4 - Contain",
      "SVP #3 - Bow",
      "SVP #1 - Absorb",
    ]
  },
  {
    id: "metal-birds",
    title: "Metal Birds",
    description: "Metalheart inspired thingy i made for postcard christmas gifts on a whim",
    images: [
      "metal-birds/metal birds 2b.png",
      "metal-birds/metal birds 10.png",
      "metal-birds/metal birds 11.png",
      "metal-birds/metal birds 12.png",
      "metal-birds/metal birds 13.png",
      "metal-birds/metal birds 14.png",
      "metal-birds/metal birds 15.png",
      "metal-birds/metal birds 16.png",
      "metal-birds/metal birds 17.png",
      "metal-birds/metal birds 18.png",
    ],
    notes: [
      "Metal Birds 2b",
      "Metal Birds 10",
      "Metal Birds 11",
      "Metal Birds 12",
      "Metal Birds 13",
      "Metal Birds 14",
      "Metal Birds 15",
      "Metal Birds 16",
      "Metal Birds 17",
      "Metal Birds 18",
    ]
  }
];
